version: '3'
services:
  portal:
    build: .
    env_file: .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
      - ./nginx/security.conf:/etc/nginx/security.conf
      - ./certs:/etc/nginx/certs
    ports:
      - '8080:443'
